---
kind: pipeline
type: docker
name: BUILD-TEST-dev
steps:
  - name: Build Multi-arch
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
      repo: alcapone1933/ddns-ipv64
      tags: dev
      dry_run: true

trigger:
  branch:
  - development
  event:
  - custom
  # - push
  # - pull_request

---
kind: pipeline
type: docker
name: BUILD-Dockerhub-dev
steps:
  - name: Build Multi-arch
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password: 
        from_secret: DOCKER_PASS    
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
      repo: alcapone1933/ddns-ipv64
      # tags: latest
      auto_tag: true
      auto_tag_suffix: dev

trigger:
  branch:
  - development
  event:
  - custom
  # - push
  # - pull_request

depends_on:
  - BUILD-TEST-DEV
