version: "3.9"
services:
  ddns-ipv64:
    # build:
      # dockerfile: ./Dockerfile
    image: alcapone1933/ddns-ipv64:latest
    # image: alcapone1933/ddns-ipv64:v0.0.5
    container_name: ddns-ipv64
    restart: always
    # volumes:
      # - data:/data
    environment:
      - "TZ=Europe/Berlin"
      # Standard Abfrage Alle 15 Minuten nach der aktuellen ip
      - "CRON_TIME=*/15 * * * *"
      # Standard Abfrage Alle 30 Minuten für die Domain Adresse 
      - "CRON_TIME_DIG=*/30 * * * *"
      - "DOMAIN_IPV64=deine-domain.ipv64.net"
      # - "DOMAIN_IPV64=deine-domain.ipv64.net,deine-domain.ipv64.de"
      - "DOMAIN_KEY=1234567890abcdefghijklmn"

# volumes:
  # data:
    # name: ddns-ipv64_data
