version: "3.9"
services:
  ddnss-cron:
    # build:
      # dockerfile: ./Dockerfile
    image: alcapone1933/ddns-ipv64:latest
    container_name: ddns-ipv64
    restart: always
    # volumes:
      # - data:/data
    environment:
      - "TZ=Europe/Berlin"
      # Standert Alle 15 Minuten
      - "CRON_TIME=*/15 * * * *"
      # Standert Alle 30 Minuten Abfrage ob der Domain eintrag richtig ist
      - "CRON_TIME_DIG=*/30 * * * *"
      - "DOMAIN_IPV64=DEINE DOMAIN https://ipv64.net/dyndns.php"
      - "DOMAIN_KEY=DEIN DOMAIN KEY bzw. DynDNS Updatehash"


# volumes:
  # data:
    # name: ddns-ipv64_data
